import type { Metadata } from "next";
import "./globals.css";
import { fontPrincipal } from "@/utils/font";
import { ThemeProvider } from "@/components/ThemeProvider";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Distiller",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${fontPrincipal.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
        <Toaster
          position="top-center"
          toastOptions={{
            classNames: {
              toast:
                "!w-[320px] !max-w-[calc(100vw-2rem)] !justify-center !text-center",
              title: "!w-full !text-center",
              description: "!w-full !text-center",
              success:
                "!bg-[#E8F5E9] !text-[#2E7D32] !border-[#C8E6C9] dark:!bg-[#102A16] dark:!text-[#A5D6A7] dark:!border-[#2E7D32]",
              error:
                "!bg-[#FDECEC] !text-[#C62828] !border-[#F5C2C2] dark:!bg-[#2A1010] dark:!text-[#EF9A9A] dark:!border-[#C62828]",

              warning:
                "!bg-[#FFF4E5] !text-[#EF6C00] !border-[#FFE0B2] dark:!bg-[#2A1A05] dark:!text-[#FFCC80] dark:!border-[#EF6C00]",
            },
          }}
        />
      </body>
    </html>
  );
}
